#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for optimizer/outline
#
# IDENTIFICATION
#    src/backend/optimizer/outline/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/optimizer/outline
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = outline_hints.o outline_plan.o outline_apply.o outline_guc.o

include $(top_srcdir)/src/backend/common.mk
